FROM oven/bun:latest

WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./bun.lockb ./bun.lockb

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./backend

RUN bun install
# echo the current working directory
RUN echo "Current working directory: $(pwd)"
# list all the files in the current directory
# RUN ls -la
# RUN cd packages && ls -la && cd ..
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:backend"]
