FROM oven/bun:latest

WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./websocket ./websocket

RUN bun install
RUN bun run db:generate

EXPOSE 8081

CMD ["bun", "run", "start:websocket"]
